import fav from '../public/assets/fav.ico'
export default function Head() {
  return (
    <>
    <title>By Abdeen</title>
    <meta name="description" content="Generated by head" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="assets/fav.ico" />
  </>
  )
}
